import Image from 'next/image'

interface BJJClass {
  title: string
    titleDe: string
      level: string
        description: string
          image: string
            imageAlt: string
              overlayImage: string
                accentColor: string
                }

                const CLASSES: BJJClass[] = [
                  {
                      title: 'Fundamentals',
                          titleDe: 'Fundamentals',
                              level: 'Anfänger · White Belt',
                                  description: 'Grundlagen und Techniken für Einsteiger und Weiße Gürtel. Der perfekte Einstieg ins BJJ.',
                                      image: '/images/hero-action.jpg',
                                          imageAlt: 'Fundamentals BJJ Training Wien',
                                              overlayImage: '/images/hero-action.jpg',
                                                  accentColor: '#6b7280',
                                                    },
                                                      {
                                                          title: 'All Levels Gi',
                                                              titleDe: 'All Levels Gi',
                                                                  level: 'Alle Levels',
                                                                      description: 'Gi-Training für alle Gürtelgrade. Technik, Sparring und Rollwork für jeden Level.',
                                                                          image: '/images/hero-action.jpg',
                                                                              imageAlt: 'Gi BJJ Training Wien',
                                                                                  overlayImage: '/images/hero-action.jpg',
                                                                                      accentColor: '#dc2626',
                                                                                        },
                                                                                          {
                                                                                              title: 'No-Gi Grappling',
                                                                                                  titleDe: 'No-Gi',
                                                                                                      level: 'Blue Belt+',
                                                                                                          description: 'Grappling ohne Gi — schnell, athletisch und dynamisch. Für Blue Belt und höher.',
                                                                                                              image: '/images/nogi-training.jpg',
                                                                                                                  imageAlt: 'No-Gi Grappling Training Wien',
                                                                                                                      overlayImage: '/images/nogi-training.jpg',
                                                                                                                          accentColor: '#2563eb',
                                                                                                                            },
                                                                                                                              {
                                                                                                                                  title: 'Kids BJJ',
                                                                                                                                      titleDe: 'Kids BJJ',
                                                                                                                                          level: '6-14 Jahre',
                                                                                                                                              description: 'BJJ für Kinder von 6 bis 14 Jahren. Disziplin, Selbstvertrauen und Spaß auf der Matte.',
                                                                                                                                                  image: '/images/kids-bjj.jpg',
                                                                                                                                                      imageAlt: 'Kids BJJ Training Wien',
                                                                                                                                                          overlayImage: '/images/kids-bjj.jpg',
                                                                                                                                                              accentColor: '#ca8a04',
                                                                                                                                                                },
                                                                                                                                                                ]

                                                                                                                                                                export function ClassesGrid() {
                                                                                                                                                                  return (
                                                                                                                                                                      <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:gap-8">
                                                                                                                                                                            {CLASSES.map((bjjClass, index) => (
                                                                                                                                                                                    <div
                                                                                                                                                                                              key={index}
                                                                                                                                                                                                        className="group bg-card rounded-2xl p-6 flex flex-col h-[320px] transition-all duration-300 hover:shadow-lg hover:-translate-y-1 border border-border/40"
                                                                                                                                                                                                                >
                                                                                                                                                                                                                          <div className="relative flex-grow flex items-center justify-center mb-4">
                                                                                                                                                                                                                                      <div className="absolute w-44 h-32 rounded-xl overflow-hidden shadow-md transform -rotate-6 transition-all duration-500 ease-in-out group-hover:-rotate-[10deg] group-hover:scale-105">
                                                                                                                                                                                                                                                    <Image
                                                                                                                                                                                                                                                                    src={bjjClass.image}
                                                                                                                                                                                                                                                                                    alt={bjjClass.imageAlt}
                                                                                                                                                                                                                                                                                                    fill
                                                                                                                                                                                                                                                                                                                    className="object-cover object-center"
                                                                                                                                                                                                                                                                                                                                    sizes="176px"
                                                                                                                                                                                                                                                                                                                                                  />
                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                          <div className="absolute w-44 h-32 rounded-xl overflow-hidden shadow-lg transform rotate-3 transition-all duration-500 ease-in-out group-hover:rotate-[5deg] group-hover:scale-105">
                                                                                                                                                                                                                                                                                                                                                                                        <Image
                                                                                                                                                                                                                                                                                                                                                                                                        src={bjjClass.overlayImage}
                                                                                                                                                                                                                                                                                                                                                                                                                        alt={bjjClass.imageAlt}
                                                                                                                                                                                                                                                                                                                                                                                                                                        fill
                                                                                                                                                                                                                                                                                                                                                                                                                                                        className="object-cover object-bottom"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        sizes="176px"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <div className="mt-auto">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <span
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                className="mb-1 inline-block text-xs font-bold uppercase tracking-widest"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              style={{ color: bjjClass.accentColor }}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        {bjjClass.level}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </span>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <h3 className="text-lg font-black text-foreground">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {bjjClass.title}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="mt-1 text-sm leading-relaxed text-muted-foreground line-clamp-2">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {bjjClass.description}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ))}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }